- name: install rabbitmq component
  hosts: rabbitmq
  become: yes  
  tasks:
  - name:  YUM Repos from the script
    ansible.builtin.shell:  "{{item}}"
    loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash



  - name: install rabbitmq-server
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed


  - name: Enable service rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      enabled: yes

  - name: Start service  if not started
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted

  - name:  create user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: setup permissions 
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"




