- name: install shipping component
  hosts: shipping
  become: yes  
  tasks:
  - name: install maven 
    ansible.builtin.yum: 
      name: maven 
      state: installed 

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop 
    register: output
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug: 
      msg: "output is : {{output}}"
  - name: print the exit status
    ansible.builtin.debug: 
      msg: "{{output.rc}}"
  - when: output.rc != 0
  - name: create user roboshop 
    become: yes  
    ansible.builtin.user:
      name: roboshop 

  - name: check app directory exists or not
    ansible.builtin.stat:
      path: /app
      register: directory
  - name: print the directory stats  
    ansible.builtin.debug:
      msg: "output is {{directory}}"

  - when: directory.stat.exists == 'false'
  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory    

  - name: download Extract
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: 
     name: mvn clean package
    args:
      chdir: /app

  - name: change name
    ansible.builtin.command: 
     name: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping 
    ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

  - name: daemon_reload 
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
  
  - name: Start service  if not started
    ansible.builtin.service:
      name: shipping
      state: restarted

  - name: Enable service shipping
    ansible.builtin.service:
      name: shipping
      enabled: yes

  - name: install mysql 
    ansible.builtin.yum: 
      name: mysql
      state: installed

  - name: load shipping data
    ansible.builtin.shell: mysql -h mysql.devopsskht.xyz -uroot -pRoboShop@1 <  /app/schema/shipping.sql  

  - name: Start service  if not started
    ansible.builtin.service:
      name: shipping
      state: restarted

  


 






      
